// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ketumobvqecjxldyiymi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtldHVtb2J2cWVjanhsZHlpeW1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3MTY3MjcsImV4cCI6MjA1MzI5MjcyN30.wpgsqkv40oms2ena5f0k5pEUQIqWXpjNPZ9RiLs8GpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);